import Head from "next/head";
import LuxuryIcon from "components/LuxuryIcon";
import SedansIcon from "components/SedansIcon";
import SuvsIcon from "components/SuvsIcon";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.ico" />
      </Head>
      <section className="p-4 flex md:h-screen md:items-center md:justify-center font-lexend">
        <div className="md:flex md:max-w-[860px] rounded-lg overflow-hidden block">
          <div className="bg-bright-orange grid gap-y-6 p-12">
            <p>
              <SedansIcon />
            </p>
            <h2 className="text-very-light-gray font-bold uppercase text-2xl">
              Sedans
            </h2>
            <p className="text-transparent-white font-lexend text-sm">
              Choose a sedan for its affordability and excellent fuel economy.
              Ideal for cruising in the city or on your next road trip.
            </p>
            <button className="md:mt-20 text-very-dark-cyan bg-very-light-gray font-semibold rounded-full w-max py-3 px-8 text-sm border border-white transition-colors hover:text-very-light-gray hover:bg-transparent">
              Learn more
            </button>
          </div>
          <div className="bg-dark-cyan grid gap-y-6 p-12">
            <p>
              <SuvsIcon />
            </p>
            <h2 className="text-very-light-gray font-bold uppercase text-2xl">
              Suvs
            </h2>
            <p className="text-transparent-white font-lexend text-sm">
              Take an SUV for its spacious interior, power, and versatility.
              Perfect for your next family vacation and off-road adventures.
            </p>
            <button className="md:mt-20 text-very-dark-cyan bg-very-light-gray font-semibold rounded-full w-max py-3 px-8 text-sm border border-white transition-colors hover:text-very-light-gray hover:bg-transparent">
              Learn more
            </button>
          </div>
          <div className="bg-very-dark-cyan grid gap-y-6 p-12">
            <p>
              <LuxuryIcon />
            </p>
            <h2 className="text-very-light-gray font-bold uppercase text-2xl">
              Luxury
            </h2>
            <p className="text-transparent-white font-lexend text-sm">
              Cruise in the best car brands without the bloated prices. Enjoy
              the enhanced comfort of a luxury rental and arrive in style.
            </p>
            <button className="md:mt-20 text-very-dark-cyan bg-very-light-gray font-semibold rounded-full w-max py-3 px-8 text-sm border border-white transition-colors hover:text-very-light-gray hover:bg-transparent">
              Learn more
            </button>
          </div>
        </div>
      </section>
    </>
  );
}
